name: geocoder_location
description: Forward and reverse geocoding.
version: 0.1.1
homepage: https://github.com/13KuntalRoy/geocode_location


dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  flutter_lints: ^1.0.4
  pedantic: ^1.11.0


flutter:

  plugin:
    platforms:
      android:
        package: com.geocoder_location.geocoder_location
        pluginClass: GeocoderLocationPlugin
      ios:
        pluginClass: GeocoderLocationPlugin
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

